(()=>{const{$,$$,toast,wsUrl,browser,model,sessionHash}=Amo1;const E={v:$('#cameraVideo'),stage:$('#cameraStage'),overlay:$('#overlay'),status:$('#status'),fps:$('#fps'),stickers:$('#stickers'),cat:$('#cat'),list:$('#list'),mood:$('#mood'),moodText:$('#moodText'),time:$('#time'),date:$('#date')};const sid=sessionHash();const S={ws:null,id:null,host:null,pc:null,dc:null,stream:null,facing:'user',timer:null,cat:'anime',idx:0,stopped:false};const sets={anime:['♡','✦','☆','૮₍ ˃ ⤙ ˂ ₎ა','猫','ꕤ','୨୧'],nature:['🌿','🌳','🦋','🐦','🐇','🍃','☀️','🌸'],background:['soft','dream','warm','cool','night']};
function send(m){if(S.ws?.readyState===1)S.ws.send(JSON.stringify(m))}function dc(m){if(S.dc?.readyState==='open')S.dc.send(JSON.stringify(m))}
function media(){return navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:S.facing},width:{ideal:1280},height:{ideal:720}},audio:false})}
function setup(){if(!S.host||S.pc)return;S.pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});if(S.stream)S.stream.getTracks().forEach(t=>S.pc.addTrack(t,S.stream));S.pc.ondatachannel=e=>bind(e.channel);S.pc.onicecandidate=e=>e.candidate&&send({type:'signal',to:S.host,data:{k:'ice',c:e.candidate}});S.pc.onconnectionstatechange=()=>{E.status.textContent=S.pc.connectionState==='connected'?'Stream live':'Stream '+S.pc.connectionState}}
async function renegotiate(){if(!S.pc||!S.host)return;try{let d=await S.pc.createOffer();await S.pc.setLocalDescription(d);send({type:'signal',to:S.host,data:{k:'offer',d:S.pc.localDescription}})}catch(e){console.warn('Renegotiation failed',e)}}
function bind(c){S.dc=c;c.onopen=()=>{E.status.textContent='Stream live';info();loc();startFrames()}}
function info(extra={}){dc({type:'device-info',info:{deviceName:'Device B · '+model(),browser:browser(),model:model(),platform:navigator.platform,...extra}})}
async function sig(d){if(!S.pc)setup();try{if(d.k==='offer'){await S.pc.setRemoteDescription(d.d);for(const c of S.icePending||[])await S.pc.addIceCandidate(c).catch(()=>{});S.icePending=[];let a=await S.pc.createAnswer();await S.pc.setLocalDescription(a);send({type:'signal',to:S.host,data:{k:'answer',d:S.pc.localDescription}})}else if(d.k==='answer'){await S.pc.setRemoteDescription(d.d)}else if(d.k==='ice'){if(S.pc.remoteDescription)await S.pc.addIceCandidate(d.c);else (S.icePending??=[]).push(d.c)}}catch(e){console.error(e)}}
function connect(){S.ws=new WebSocket(wsUrl());S.ws.onopen=()=>{if(!sid)return toast('Invalid QR');send({type:'join-session',sessionId:sid})};S.ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='hello')S.id=m.peerId;if(m.type==='joined'){S.host=m.hostPeerId;setup()}if(m.type==='signal')sig(m.data);if(m.type==='session-ended')stop(false);if(m.type==='error')toast(m.message)};S.ws.onerror=()=>toast('Signaling unavailable')}
async function start(){if(S.stream)return true;try{S.stream=await media();E.v.srcObject=S.stream;E.v.dataset.rear=S.facing==='environment';await E.v.play().catch(()=>{});E.overlay.classList.add('hidden');E.stage.classList.add('live');if(!S.pc)setup();else{let s=S.pc.getSenders().find(x=>x.track?.kind==='video');if(s)await s.replaceTrack(S.stream.getVideoTracks()[0]);else{S.pc.addTrack(S.stream.getVideoTracks()[0],S.stream);if(S.pc.signalingState==='stable')renegotiate()}}info();loc();startFrames();return true}catch(e){toast(e.name==='NotAllowedError'?'Camera permission denied':'Camera could not start');return false}}
async function flip(){if(!(await start()))return;let old=S.stream;S.facing=S.facing==='user'?'environment':'user';try{let n;try{n=await media()}catch(e){old.getTracks().forEach(t=>t.stop());n=await media()}let t=n.getVideoTracks()[0],s=S.pc?.getSenders().find(x=>x.track?.kind==='video');if(s)await s.replaceTrack(t);S.stream=n;E.v.srcObject=n;E.v.dataset.rear=S.facing==='environment';await E.v.play().catch(()=>{});old.getTracks().forEach(x=>x.stop());toast(S.facing==='environment'?'Back camera':'Front camera')}catch(e){S.facing=S.facing==='user'?'environment':'user';toast('Could not switch camera')}}
function frame(){if(!S.stream||S.dc?.readyState!=='open'||!E.v.videoWidth)return;let c=document.createElement('canvas'),w=400,h=225;c.width=w;c.height=h;c.getContext('2d').drawImage(E.v,0,0,w,h);c.toBlob(b=>{if(!b||S.dc.bufferedAmount>500000)return;let r=new FileReader();r.onload=()=>dc({type:'frame',data:r.result,createdAt:Date.now()});r.readAsDataURL(b)},'image/jpeg',.4)}
function startFrames(){if(S.timer)return;S.timer=setInterval(frame,500);E.fps.textContent='2f/s capture: on'}
function photo(){if(!S.stream)return toast('Start camera first');if(S.dc?.readyState!=='open')return toast('Device A not connected');let c=document.createElement('canvas'),w=E.v.videoWidth||1280,h=E.v.videoHeight||720;c.width=w;c.height=h;c.getContext('2d').drawImage(E.v,0,0,w,h);c.toBlob(b=>{let r=new FileReader();r.onload=()=>dc({type:'photo',data:r.result,mime:'image/jpeg',createdAt:Date.now()});r.readAsDataURL(b)},'image/jpeg',.88)}
function loc(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>info({location:{lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}}),()=>{}, {enableHighAccuracy:true,timeout:12000,maximumAge:0})}
function render(){let a=sets[S.cat];E.cat.textContent=S.cat[0].toUpperCase()+S.cat.slice(1);E.list.innerHTML='';a.forEach((x,i)=>{let b=document.createElement('button');b.textContent=x;b.className=i===S.idx?'active':'';b.onclick=()=>{S.idx=i;render()};E.list.append(b)});E.stickers.textContent=S.cat==='background'?'':a[S.idx];E.stage.dataset.bg=S.cat==='background'?a[S.idx]:''}
function cycle(n){S.idx=(S.idx+n+sets[S.cat].length)%sets[S.cat].length;render()}
function clock(){let d=new Date();E.time.textContent=d.toLocaleTimeString();E.date.textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'})}
function stop(show=true){S.stopped=true;clearInterval(S.timer);S.stream?.getTracks().forEach(t=>t.stop());S.pc?.close();S.dc?.close();S.ws?.close();E.v.srcObject=null;E.overlay.classList.remove('hidden');E.status.textContent='Stopped';if(show)toast('Stopped')}
$('#camera').onclick=start;$('#flip').onclick=flip;$('#photo').onclick=photo;$('#prev').onclick=()=>cycle(-1);$('#next').onclick=()=>cycle(1);$('#stop').onclick=()=>stop();$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.cat=b.dataset.cat;S.idx=0;render()});render();clock();setInterval(clock,1000);if(sid)connect();else E.status.textContent='Invalid QR'})()