(()=>{const{$,toast,copy,wsUrl}=Amo1;const E={qr:$('#qr'),url:$('#url'),count:$('#count'),conn:$('#conn'),connText:$('#connText'),loc:$('#loc'),lat:$('#lat'),lng:$('#lng'),stage:$('#stage'),empty:$('#empty'),title:$('#streamTitle'),devices:$('#devices'),gallery:$('#gallery'),photos:$('#photos')};
const S={ws:null,id:null,sid:null,exp:0,peers:new Map(),selected:null,ended:false,chosen:new Set()};
const ice={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
function send(m){if(S.ws?.readyState===1)S.ws.send(JSON.stringify(m))}
function url(){let u=new URL('./camera.html',location.href);u.hash='session='+encodeURIComponent(S.sid);return u.href}
function qr(){let img=document.createElement('img');img.src='https://api.qrserver.com/v1/create-qr-code/?size=520x520&data='+encodeURIComponent(url());E.qr.replaceChildren(img);E.url.textContent=url()}
function peer(id){if(S.peers.has(id))return S.peers.get(id);let p={id,pc:new RTCPeerConnection(ice),dc:null,stream:null,info:{},pending:[],remote:false};S.peers.set(id,p);if(S.selected===null)S.selected=id;
p.pc.onicecandidate=e=>e.candidate&&send({type:'signal',to:id,data:{k:'ice',c:e.candidate}});
p.pc.ontrack=e=>{p.stream=e.streams[0]||new MediaStream([e.track]);show(p);drawDevices()};
p.pc.ondatachannel=e=>bindDC(p,e.channel);p.pc.onconnectionstatechange=()=>drawDevices();return p}
async function offer(id){let p=peer(id);try{if(!p.dc)bindDC(p,p.pc.createDataChannel('amo1-data'));p.pc.addTransceiver('video',{direction:'recvonly'});const d=await p.pc.createOffer();await p.pc.setLocalDescription(d);send({type:'signal',to:id,data:{k:'offer',d:p.pc.localDescription}})}catch(e){console.error('Offer failed',e);toast('Could not start WebRTC')}}
function bindDC(p,c){p.dc=c;c.onopen=()=>{};c.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='device-info'){p.info={...p.info,...m.info};drawDevices();locationUI(p.info.location)}if(m.type==='location'){p.info.location=m.location;locationUI(m.location)}if(m.type==='photo')savePhoto(p,m)}}
async function signal(from,d){let p=peer(from);try{if(d.k==='offer'){await p.pc.setRemoteDescription(d.d);p.remote=true;for(const c of p.pending)await p.pc.addIceCandidate(c).catch(()=>{});p.pending=[];let a=await p.pc.createAnswer();await p.pc.setLocalDescription(a);send({type:'signal',to:from,data:{k:'answer',d:p.pc.localDescription}})}else if(d.k==='answer'){await p.pc.setRemoteDescription(d.d);p.remote=true;for(const c of p.pending)await p.pc.addIceCandidate(c).catch(()=>{});p.pending=[]}else if(d.k==='ice'){if(p.remote)await p.pc.addIceCandidate(d.c);else p.pending.push(d.c)}}catch(e){console.error(e)}}
function msg(m){if(m.type==='hello'){S.id=m.peerId;send({type:'create-session'});return}if(m.type==='session-created'){S.sid=m.sessionId;S.exp=m.expiresAt;qr();timer();return}if(m.type==='peer-joined'){peer(m.peerId);drawDevices();offer(m.peerId);return}if(m.type==='peer-left'){remove(m.peerId);return}if(m.type==='signal')signal(m.from,m.data);if(m.type==='device-info'){let p=peer(m.from);p.info={...p.info,...m.info};drawDevices();locationUI(p.info.location)}if(m.type==='session-ended')endLocal()}
function connect(){S.ws=new WebSocket(wsUrl());S.ws.onmessage=e=>{try{msg(JSON.parse(e.data))}catch{}};S.ws.onerror=()=>toast('Signaling server unavailable');S.ws.onclose=()=>{if(!S.ended){E.connText.textContent='Signaling disconnected — refresh Device A';toast('Signaling disconnected')}}}
function timer(){setInterval(()=>{let l=Math.max(0,S.exp-Date.now());E.count.textContent=String(Math.floor(l/60000)).padStart(2,'0')+':'+String(Math.floor(l%60000/1000)).padStart(2,'0');if(!l)endLocal()},250)}
function show(p){E.empty.classList.add('hidden');E.title.textContent=(p.info.deviceName||'Device B')+' · live';let v=E.stage.querySelector('video.remote');if(!v){v=document.createElement('video');v.className='remote';v.autoplay=true;v.playsInline=true;v.muted=true;E.stage.append(v)}v.srcObject=p.stream;v.play().catch(()=>{});p.video=v}
function drawDevices(){E.devices.innerHTML='';for(const p of S.peers){let b=document.createElement('button');b.className=S.selected===p[0]?'active':'';b.textContent=(p[1].info.deviceName||'Device B')+' · '+(p[1].pc.connectionState||'connecting');b.onclick=()=>{S.selected=p[0];show(p[1]);locationUI(p[1].info.location);drawDevices()};E.devices.append(b)}E.conn.textContent=S.peers.size?S.peers.size+' device(s) connected':'Waiting';E.connText.textContent=S.peers.size?'Camera session active':'Scan the QR on Device B'}
function locationUI(l){if(!l){E.loc.textContent='Waiting';return}E.loc.textContent='Location received';E.lat.textContent=Number(l.lat).toFixed(6);E.lng.textContent=Number(l.lng).toFixed(6)}
function savePhoto(p,m){let r=indexedDB.open('amo1photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('p',{keyPath:'id'});r.onsuccess=()=>{let d=r.result,t=d.transaction('p','readwrite');t.objectStore('p').put({id:Date.now()+Math.random(),data:m.data,name:p.info.deviceName||'Device B'});t.oncomplete=gallery;}}
function gallery(){let r=indexedDB.open('amo1photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('p',{keyPath:'id'});r.onsuccess=()=>{let d=r.result,g=d.transaction('p').objectStore('p').getAll();g.onsuccess=()=>{E.photos.textContent=g.result.length;E.gallery.innerHTML='';g.result.slice(-12).reverse().forEach(x=>{let b=document.createElement('button');b.innerHTML='<img src="'+x.data+'"><small>'+x.name+'</small>';b.onclick=()=>S.chosen.add(x.id);E.gallery.append(b)})}}}
function remove(id){let p=S.peers.get(id);try{p.pc.close()}catch{}S.peers.delete(id);drawDevices()}
function endLocal(){S.ended=true;for(const p of S.peers.values())try{p.pc.close()}catch{}S.peers.clear();S.ws?.close();toast('Session ended')}
$('#delete').onclick=()=>{if(!S.chosen.size)return toast('Select photos first');let r=indexedDB.open('amo1photos',1);r.onsuccess=()=>{let t=r.result.transaction('p','readwrite');for(const id of S.chosen)t.objectStore('p').delete(id);t.oncomplete=()=>{S.chosen.clear();gallery()}}};$('#copy').onclick=()=>S.sid?copy(url()):toast('QR not ready');$('#share').onclick=()=>navigator.share?navigator.share({url:url(),title:'Amo1'}):copy(url());$('#end').onclick=()=>{send({type:'end-session'});endLocal()};$('#regen').onclick=()=>location.reload();$('#map').onclick=()=>{let l=S.peers.get(S.selected)?.info.location;if(l)window.open('https://www.openstreetmap.org/?mlat='+l.lat+'&mlon='+l.lng,'_blank')};gallery();connect()})()